# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Почта подтверждена')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Профиль активен (имеется вся информация)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар профиля')),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на аватар профиля')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон должен быть заполнен в формате: '+999999999'. Максимум 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Контактный телефон')),
                ('profile_type', models.CharField(choices=[('ST', 'Ученик'), ('TH', 'Учитель'), ('PR', 'Родитель')], default='ST', max_length=2, verbose_name='Тип пользователя')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Класс')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведние')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'данные пользователя',
                'verbose_name_plural': 'данные пользователя',
            },
        ),
    ]
