FROM alpine

# Setup
RUN apk update
RUN apk upgrade
RUN apk add --update python3 python3-dev postgresql-client postgresql-dev build-base gettext jpeg-dev zlib-dev build-base
RUN pip3 install --upgrade pip

# Create basic project structure
RUN mkdir -p /code/
WORKDIR /code

ADD backend/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

EXPOSE 8000