# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название урока')),
                ('about', models.TextField(verbose_name='Описание урока')),
                ('time', models.PositiveSmallIntegerField(default=20, verbose_name='Время на урок')),
                ('subject_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectTag')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='LessonNodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Node')),
            ],
            options={
                'verbose_name': 'включение узла в урок',
                'verbose_name_plural': 'включения узла в урок',
            },
        ),
    ]
