# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'блок', 'verbose_name_plural': 'блоки'},
        ),
        migrations.AlterModelOptions(
            name='choiceblockoption',
            options={'verbose_name': 'вариант ответа на тестовый вопрос', 'verbose_name_plural': 'варианты ответа на тестовые вопросы'},
        ),
    ]
