# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blocks', '0002_auto_20170710_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_blocks.block_set+', to='contenttypes.ContentType'),
        ),
    ]
