# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задание для ученика', 'verbose_name_plural': 'задания для ученика'},
        ),
    ]
