# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjecttag',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
    ]
