# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название объекта')),
                ('subject_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectTag')),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': 'Узлы',
            },
        ),
        migrations.CreateModel(
            name='NodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_in_node_relation', to='nodes.Node', verbose_name='Child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_in_node_relation', to='nodes.Node', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Связь между узлами',
                'verbose_name_plural': 'Связи между узлами',
            },
        ),
    ]
