# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderelation',
            name='relation_type',
            field=models.CharField(choices=[('ST', 'Сильная'), ('WK', 'Слабая')], default='WK', max_length=2, verbose_name='Тип связи'),
        ),
    ]
