# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_noderelation_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('DF', 'Понятие'), ('MT', 'Метод')], default='DF', max_length=2, verbose_name='Тип узла'),
        ),
    ]
